import { css } from "remix/ui";

import { t } from "../theme.ts";

let display = '"Instrument Sans", ui-sans-serif, system-ui, sans-serif';

export let home = css<HTMLDivElement>({
    background: t.color.canvas,
    color: t.color.text,
    minHeight: "100vh",
    padding: `${t.size.header} clamp(1rem, 4vw, 4.5rem) 0`,
    "& a": { color: "inherit" },
    "& a:focus-visible, & button:focus-visible, & input:focus-visible": {
        outline: `${t.size.focus} solid ${t.color.link}`,
        outlineOffset: t.spacing(1),
    },
    "& main, & footer": { maxWidth: "1360px", marginInline: "auto" },
    "& [data-home-brand]": {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "4rem",
        marginBottom: "1.75rem",
    },
    "& [data-home-brand] > span": { gap: "1rem" },
    "& [data-home-brand] svg": { height: "clamp(1.75rem, 3vw, 2.5rem)", width: "auto" },
    "& [data-home-hero]": {
        display: "grid",
        gridTemplateColumns: "1.05fr 1fr",
        alignItems: "center",
        gap: "3.5rem",
        paddingBlock: "4.5rem 4rem",
        borderBottom: `1px solid ${t.color.border}`,
    },
    "& [data-hero-copy]": { minWidth: 0 },
    "& [data-team-label]": {
        fontFamily: t.font.mono,
        textTransform: "uppercase",
        fontSize: "0.75rem",
        color: t.color.secondary,
        margin: "0 0 1.75rem",
    },
    "& [data-team-label] span": { color: t.color.brand, marginRight: "0.5rem" },
    "& h1": {
        fontFamily: display,
        fontWeight: 550,
        fontSize: "clamp(2.75rem, 4.5vw, 4.75rem)",
        lineHeight: 1.08,
        letterSpacing: "-0.045em",
        margin: 0,
        textWrap: "balance",
    },
    "& h1 em": { fontStyle: "normal", color: t.color.brand },
    "& [data-hero-description]": {
        maxWidth: "31rem",
        margin: "1.75rem 0 2rem",
        fontSize: "1.125rem",
        lineHeight: 1.6,
        color: t.color.secondary,
    },
    "& [data-hero-actions]": {
        display: "flex",
        alignItems: "center",
        gap: "1.75rem",
        flexWrap: "wrap",
    },
    "& [data-secondary-action]": { fontSize: "0.875rem", textUnderlineOffset: "0.4em" },
    "& [data-secondary-action]:hover": { color: t.color.linkHover },
    "& [data-hero-footnote]": {
        display: "flex",
        flexWrap: "wrap",
        gap: "1.5rem",
        marginTop: "2.5rem",
        fontFamily: t.font.mono,
        fontSize: "0.625rem",
        color: t.color.secondary,
    },
    "& [data-home-section]": { paddingBlock: "4rem", scrollMarginTop: t.size.anchorOffset },
    "& [data-home-section] + [data-home-section]": { borderTop: `1px solid ${t.color.border}` },
    "& [data-deployment-grid]": {
        display: "grid",
        gridTemplateColumns: "1fr 1.35fr",
        border: `1px solid ${t.color.border}`,
        borderRadius: t.radius.panel,
        background: t.color.surface,
        overflow: "hidden",
    },
    "& [data-deployment-intro]": { padding: "2rem", alignSelf: "center" },
    "& [data-deployment-intro] > span": {
        fontFamily: t.font.mono,
        fontSize: "0.6875rem",
        textTransform: "uppercase",
    },
    "& [data-deployment-intro] > p": { fontSize: "1.5rem", lineHeight: 1.3, margin: "1.5rem 0" },
    "& [data-deployment-intro] > a": {
        color: t.color.secondary,
        fontSize: "0.8125rem",
        textUnderlineOffset: "0.3em",
    },
    "& [data-deployment] ul": {
        listStyle: "none",
        margin: 0,
        padding: 0,
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        borderLeft: `1px solid ${t.color.border}`,
    },
    "& [data-deployment] li": { minWidth: 0 },
    "& [data-deployment] li:nth-child(2n)": { borderLeft: `1px solid ${t.color.border}` },
    "& [data-deployment] li:nth-child(n+3)": { borderTop: `1px solid ${t.color.border}` },
    "& [data-deployment] li a": {
        display: "grid",
        gridTemplateColumns: "1fr auto",
        gap: "0.25rem 0.5rem",
        padding: "1.25rem",
        textDecoration: "none",
    },
    "& [data-deployment] li a:hover": { background: t.color.surface, color: t.color.linkHover },
    "& [data-deployment] li small": {
        gridColumn: 1,
        gridRow: 2,
        fontFamily: t.font.mono,
        color: t.color.secondary,
        fontSize: "0.6875rem",
    },
    "& [data-deployment] li a > :last-child": {
        gridColumn: 2,
        gridRow: "1 / 3",
        alignSelf: "center",
        color: t.color.secondary,
    },
    "& [data-home-close]": {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        gap: "2rem",
        marginBlock: "1rem 3rem",
        padding: "3rem",
        border: `${t.size.hairline} solid ${t.color.border}`,
        borderRadius: t.radius.panel,
        background: t.color.surface,
        color: t.color.text,
    },
    "& [data-home-close] p": {
        fontFamily: t.font.mono,
        fontSize: "0.6875rem",
        margin: "0 0 1rem",
        textTransform: "uppercase",
    },
    "& [data-home-close] h2": {
        fontFamily: display,
        fontSize: "clamp(2.25rem, 4vw, 3.75rem)",
        fontWeight: 550,
        lineHeight: 1.08,
        margin: 0,
    },
    "& [data-home-footer]": {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        flexWrap: "wrap",
        gap: "1.5rem",
        paddingBlock: "0 2.5rem",
        fontSize: "0.75rem",
        color: t.color.secondary,
    },
    "& [data-home-footer] > div": { display: "flex", gap: "1.5rem", flexWrap: "wrap" },
    "& [data-home-footer] a": { textUnderlineOffset: "0.25em" },
    "@media (max-width: 1050px)": {
        "& [data-home-hero]": { gap: "2rem" },
        "& [data-hero-actions]": { gap: "1.25rem" },
    },
    "@media (max-width: 820px)": {
        "& [data-home-hero]": { gridTemplateColumns: "1fr", paddingBlock: "2.5rem", gap: "2.5rem" },
        "& h1": { fontSize: "clamp(2.5rem, 9vw, 4.75rem)" },
        "& [data-hero-description]": { maxWidth: "36rem" },
        "& [data-deployment-grid]": { gridTemplateColumns: "1fr" },
        "& [data-deployment] ul": { borderLeft: 0, borderTop: `1px solid ${t.color.border}` },
        "& [data-home-close]": {
            padding: "2rem",
            alignItems: "flex-start",
            flexDirection: "column",
        },
        "& [data-home-footer] > span": { flexBasis: "100%", order: 1 },
    },
    "@media (max-width: 480px)": {
        "& [data-team-label]": { marginBottom: "1.25rem", fontSize: "0.6875rem" },
        "& [data-hero-description]": { fontSize: "1rem" },
        "& [data-hero-footnote]": { gap: "1rem", fontSize: "0.5625rem" },
        "& [data-home-section]": { paddingBlock: "2.5rem" },
        "& [data-deployment-intro]": { padding: "1.5rem" },
        "& [data-deployment] li a": { padding: "1rem", fontSize: "0.875rem" },
    },
});

export let action = css<HTMLAnchorElement>({
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "2rem",
    padding: "0.85rem 1.25rem",
    minHeight: "48px",
    background: t.color.action.background,
    color: t.color.action.text,
    fontSize: "0.9375rem",
    fontWeight: 650,
    textDecoration: "none",
    whiteSpace: "nowrap",
    border: `${t.size.hairline} solid ${t.color.action.background}`,
    borderRadius: t.radius.md,
    transition: `background-color ${t.duration.fast} ${t.ease.standard}`,
    "&:hover": { background: t.color.action.hover },
});

export let sectionHeading = css<HTMLDivElement>({
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: "2rem",
    marginBottom: "2rem",
    "& h2": {
        fontFamily: display,
        fontSize: "clamp(2rem, 3vw, 3rem)",
        fontWeight: 550,
        lineHeight: 1.15,
        margin: 0,
    },
    "& h2 span": { color: t.color.secondary },
    "& p": { margin: 0, color: t.color.secondary, fontSize: "0.9375rem", maxWidth: "22rem" },
    "@media (max-width: 820px)": { alignItems: "flex-start", flexDirection: "column", gap: "1rem" },
});
