import { css } from "remix/ui";

import { t } from "../theme.ts";

export let workbench = css<HTMLDivElement>({
    display: "grid",
    gridTemplateColumns: "17rem minmax(0, 1fr)",
    border: `1px solid ${t.color.border}`,
    background: t.color.surface,
    borderRadius: t.radius.panel,
    overflow: "hidden",
    "& [data-workbench-bar], & [data-workbench-footer]": {
        display: "flex",
        justifyContent: "space-between",
        gap: "1rem",
        gridColumn: "1 / -1",
        padding: "0.75rem 1.25rem",
        fontFamily: t.font.mono,
        fontSize: "0.6875rem",
        color: t.color.secondary,
    },
    "& [data-workbench-bar]": { borderBottom: `1px solid ${t.color.border}` },
    "& [data-workbench-bar] > :first-child": {
        color: t.color.accent,
        textTransform: "uppercase",
    },
    "& [data-workbench-footer]": {
        borderTop: `1px solid ${t.color.border}`,
        textTransform: "uppercase",
    },
    "& [data-package-options]": {
        minWidth: 0,
        border: 0,
        borderRight: `1px solid ${t.color.border}`,
        padding: 0,
        margin: 0,
    },
    "& [data-package-legend]": {
        float: "left",
        width: "100%",
        color: t.color.secondary,
        padding: "1.25rem",
        fontSize: "0.8125rem",
        margin: 0,
    },
    "& [data-package-choice]": {
        clear: "both",
        position: "relative",
        width: "100%",
        border: 0,
        background: "transparent",
        font: "inherit",
        textAlign: "start",
        display: "flex",
        gap: "0.75rem",
        alignItems: "center",
        padding: "1rem 1.25rem",
        minHeight: "4.4rem",
        borderTop: `1px solid ${t.color.border}`,
        cursor: "pointer",
        transition: "background-color 120ms ease-out",
    },
    "& [data-package-choice]:hover": { backgroundColor: t.color.hover },
    "& [data-package-choice]:has(input:checked), & [data-package-choice][aria-selected='true']": {
        backgroundColor: t.color.linkCurrent,
    },
    "& label:has(input:checked) strong, & [aria-selected='true'] strong": { color: t.color.link },
    "& label:has(input:focus-visible), & [data-package-choice]:focus-visible": {
        outline: `2px solid ${t.color.link}`,
        outlineOffset: "-2px",
    },
    "& input": {
        position: "absolute",
        width: "1px",
        height: "1px",
        opacity: 0,
    },
    "& strong": {
        display: "block",
        fontFamily: t.font.mono,
        fontSize: "0.8125rem",
        fontWeight: 500,
        color: t.color.text,
    },
    "& small": {
        display: "block",
        fontSize: "0.8125rem",
        color: t.color.secondary,
        marginTop: "0.25rem",
    },
    "& [data-package-panels]": {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr)",
        minWidth: 0,
    },
    "& [data-code-package]": {
        gridArea: "1 / 1",
        minWidth: 0,
        visibility: "hidden",
        padding: "1.5rem 2rem 2rem",
    },
    ...Object.fromEntries(
        ["dev", "content", "theme", "crawler", "d1"].map(id => [
            `&:has(input[value="${id}"]:checked) [data-code-package="${id}"], &:has([data-package="${id}"][aria-selected="true"]) [data-code-package="${id}"]`,
            { visibility: "visible" },
        ]),
    ),
    "& h3": { fontSize: "1.375rem", margin: 0, fontWeight: 500 },
    "& section > p": { fontSize: "0.9375rem", color: t.color.secondary, margin: "0.5rem 0 1.5rem" },
    "& section > a": {
        display: "inline-block",
        marginTop: "1.5rem",
        fontSize: "0.875rem",
        color: t.color.link,
        textUnderlineOffset: "0.3em",
    },
    "& section > a:hover": { color: t.color.linkHover },
    "& .expressive-code": { fontSize: "0.8125rem" },
    "@media (max-width: 760px)": {
        gridTemplateColumns: "minmax(0, 1fr)",
        "& [data-package-options]": {
            display: "flex",
            flexDirection: "column",
            borderRight: 0,
            borderBottom: `1px solid ${t.color.border}`,
        },
        "& [data-package-options][data-enhanced='true']": {
            flexDirection: "row",
            overflowX: "auto",
        },
        "& [data-package-legend]": { display: "none" },
        // The bar above already draws the rule; stacked choices divide each other.
        "& [data-package-choice]": {
            padding: "0.75rem 1rem",
            flex: "0 0 auto",
            width: "auto",
            minHeight: "3.5rem",
            borderTop: 0,
        },
        "& [data-package-options]:not([data-enhanced='true']) [data-package-choice] + [data-package-choice]":
            { borderTop: `1px solid ${t.color.border}` },
        "& strong": { fontSize: "0.75rem" },
        "& small": { display: "none" },
        "& [data-code-package]": { padding: "1.25rem 1rem" },
        "& [data-workbench-bar], & [data-workbench-footer]": {
            fontSize: "0.625rem",
            flexWrap: "wrap",
        },
    },
});
