/**
 * Compiles `data-table` migrations into the flat `.sql` files Wrangler's D1
 * migration runner reads.
 *
 * Node-only build tooling. Nothing here belongs in a Worker bundle, which is
 * why it is a separate entry point from the driver.
 *
 * @module @pitlane/data-table-d1/migrations
 */
import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { loadMigrations } from "remix/data-table/migrations/node";

/**
 * What {@link generateD1Migrations} needs to know.
 */
export interface GenerateD1MigrationsOptions {
    /**
     * Directory holding the `data-table` migrations, one `<id>_<name>/`
     * directory per migration.
     *
     * @default "db/migrations"
     */
    from?: string;

    /**
     * Where the generated `.sql` files land. Point this at the same directory
     * as `migrations_dir` in your Wrangler config.
     */
    to: string;
}

/**
 * One generated file.
 */
export interface GeneratedD1Migration {
    /** Migration id, typically a `YYYYMMDDHHmmss` timestamp. */
    id: string;
    /** Migration slug. */
    name: string;
    /** Path of the written file, relative to the working directory. */
    file: string;
}

/**
 * A generated file, as opposed to a `.gitkeep` or a `README.md` that happens to
 * sit in the same directory. Matches Wrangler's own migration filename shape.
 */
const GENERATED = /^\d{4,14}_.+\.sql$/;

/**
 * Writes one `<id>_<name>.sql` per migration into `options.to`, then deletes
 * generated files with no migration behind them, so the output directory is a
 * pure function of the input one.
 *
 * The SQL is copied verbatim. Splitting it into statements is the job of
 * whatever executes the file, and a splitter naive enough to write here would
 * corrupt any migration containing a semicolon inside a string literal or a
 * `begin ... end` trigger body.
 *
 * @param options Where to read migrations from, and where to write SQL to.
 * @returns The generated files, ordered by migration id.
 * @throws If `options.from` holds no migrations, or one of them has an empty
 * `up`. Both mean the output directory is about to be wrong, and a migration
 * runner is the worst place to discover that.
 *
 * @example
 * ```ts
 * import { generateD1Migrations } from "@pitlane/data-table-d1/migrations";
 *
 * await generateD1Migrations({ to: "db/d1-migrations" });
 * ```
 */
export async function generateD1Migrations(
    options: GenerateD1MigrationsOptions,
): Promise<GeneratedD1Migration[]> {
    let from = path.resolve(options.from ?? "db/migrations");
    let to = path.resolve(options.to);

    let migrations = await loadMigrations(from);
    if (migrations.length === 0) {
        throw new Error(`[@pitlane/data-table-d1] no migrations found in ${from}`);
    }

    await mkdir(to, { recursive: true });

    let generated: GeneratedD1Migration[] = [];
    for (let migration of migrations) {
        if (migration.up.trim().length === 0) {
            throw new Error(
                `[@pitlane/data-table-d1] migration ${migration.id}_${migration.name} has an empty \`up\``,
            );
        }

        let filename = `${migration.id}_${migration.name}.sql`;
        let file = path.join(to, filename);
        await writeFile(file, header(migration.id, migration.name) + migration.up.trimEnd() + "\n");

        generated.push({
            id: migration.id,
            name: migration.name,
            file: path.relative(process.cwd(), file),
        });
    }

    await pruneStale(to, new Set(generated.map(entry => path.basename(entry.file))));

    return generated;
}

function header(id: string, name: string): string {
    return (
        `-- Generated by @pitlane/data-table-d1 from ${id}_${name}/up.sql.\n` +
        "-- Do not edit by hand; re-run the generator instead.\n\n"
    );
}

async function pruneStale(directory: string, keep: Set<string>): Promise<void> {
    for (let entry of await readdir(directory)) {
        if (!GENERATED.test(entry) || keep.has(entry)) continue;
        await unlink(path.join(directory, entry));
    }
}
