name: 🛠️ Build & Deploy to Cloudflare Workers

on:
    push:
        branches:
            - main

permissions:
    contents: read
    deployments: write

# use the GitHub repo name as the Workers project name
env:
    PROJECT_NAME: ${{ github.event.repository.name }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 📥 Checkout code
              uses: actions/checkout@v4

            - name: ⚡️ Setup Vite+
              uses: voidzero-dev/setup-vp@v1
              with:
                  cache: true

            - name: 🚀 Build docs (VitePress)
              run: vp run docs:build

            - name: ☁️ Deploy Worker
              run: vpx wrangler deploy --name=${{ env.PROJECT_NAME }} --config wrangler.jsonc
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
